### PR TITLE
Nh downsample sam n reads

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
@tfenne this is a preview for discussion prior to making a PR to broadinstitute/picard.  Could you take a look.  In particular, I am worried about if there are secondary or supplementary reads, the fraction retained could be underestimated.

**Comment by tfenne** [comment]
I feel pretty strongly that this should not be a change to `DownsampleSam`, but a separate tool that either extends `DownsampleSam` or just leverages the `DownamplingIterator` stuff internally.  My reasoning being:
1. This nearly doubles the actual working code in the class
2. It's a very different mode of operation
3. It may cause it to be two-pass over the BAM, and even in one-pass mode it requires the index which breaks streaming
4. As you point out, it's complicated when there are secondary and supplemental reads.

I think it would be trivial to make it a second tool, and then you could write extensive usage and parameter documentation that was specific to the "downsample to N" usecase and make it really clear how it works, without making the documentation for `DownsampleSam` any more confusing.

**Comment by nh13** [comment]
@tfenne just a quick question about `DownsampleSam` since your the author.  It says that secondary alignments are discarded in the usage, but I don't think this is the case.  I don't see any usages of `getNotPrimaryAlignmentFlag` or `isSecondaryOrSupplementary` in any of the `DownsamplingIterator` code.  What am I missing?

**Comment by nh13** [comment]
@tfenne another interesting thing that I want to confirm is that the proportion provide to `DownsampleSam` is the proportion of unique read names, whereas the `DownsamplingIterator` returns statistics based on records, so the final message in `DownsampleSam` is confusing.  Consider a really simple scenario of one paired end read and one fragment read in the same SAM file.  If we say a `0.5` proportion, we get either the paired end read or the fragment read, but not both (with sufficient accuracy).  The number of records accepted is either `2` or `1`, but the number of reads (templates) is `1`.  The reason to belaborer this distinction is to say that I think that `DownsamplingIteratorTests` are wrong for the secondary test, since `getAcceptedFraction` includes secondary records.  Maybe it's late and I am not understanding the code in htsjdk correctly, could you help me out?

**Pull request closed without merging**
