### PR TITLE
Supporting auxiliary baits for bait re-design

### PR DESCRIPTION
**Pull request by nh13**
@tfenne and @yfarjoun I wanted to get your opinion on if these two commits would be useful to pull into Picard before cleaning them up (ignore the names and such) and adding tests.

The first commit updates `BaitDesigner` to take in an auxiliary set of targets and baits, and includes them when performing the final assessment of the design.  This is useful if we are only re-designing a subset of the targets, but want to include all targets in the final design calculations and metrics.

The second commit adds the `COVERED` action to `IntervalListTools`.  I would be OK with pushing down the action into `htsjdk` (at @tfenne's blessing) too.  I am using this new action in a similar vein as above, where I want to find the sub-set of the original baits that are "near" the well-performing/passing targets and so do not need to be re-designed. 

With these two changes, I can take my two lists of passing and failing targets, find the baits that cover the passing and failing targets respectively, then redesign the failing targets, and combing the original passing baits with the newly design baits for the failing targets.  Phew!

### CODE REVIEW

**Comment by yfarjoun** [comment]
@nh13 I have :zero: experience using BaitDesigner....so while your example sounds compelling and useful, I do not feel that I can add much to it. 

 I think that the "Covered" action in interval list tool is great! I think it can be used for other things too and would be happy to have it included. I would call it "OVERLAPS" and not "COVERED"...

**Comment by nh13** [comment]
The interval list work is here: https://github.com/samtools/htsjdk/pull/877

**Comment by nh13** [comment]
Moved the change to `IntervalListTools` to https://github.com/broadinstitute/picard/pull/830.

**Comment by nh13** [comment]
Moving to https://github.com/broadinstitute/picard/pull/830 and https://github.com/broadinstitute/picard/pull/831.

**Pull request closed without merging**
